name: codon_analyzer_base
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21
  - pandas=1.3
  - scipy=1.7
  - matplotlib=3.4
  - seaborn=0.11
  - scikit-learn=1.0
  - biopython=1.79
  - pybedtools=0.9
  - pysam=0.17
  - h5py=3.6
  - tqdm=4.62
  - click=8.0
  - pyyaml=6.0
  - jinja2=3.0
  - markdown=3.3
  - pip
  - pip:
    - pyfastx==0.8.4
    - codon-usage==1.0.0
    - snakemake==7.18.2